### ISSUE TITLE
fix: menu page and post 404s

### ISSUE THREAD

**Issue by johhansantana** [postlight/headless-wp-starter#21]
First of all, I gotta admit this is one of the coolest libraries I've seen around. I've been using nextjs for the past year but I got little to no clue on how WordPress works as an API backend. Hopefully, I can contribute a bit on the nextjs part when I get some free time.

So for the bugs, I've recorded a small gif that displays the 2 of them that I found initially by just installing the dependencies and running the project and adding a new page:

![wordpressheadless](https://user-images.githubusercontent.com/9933887/32841884-18ebd8a2-c9c8-11e7-80c7-b4620b9edb3e.gif)

As you can see, when clicking on a page it will show a 404 not found for a second and then renders the page correctly.

The second one is when adding a new menu page it will direct you to the wrong URL and it will not find the correct path since the 404 error.

That's all, looking forward to being able to use this in the future! Thanks!

**Comment by ginatrapani** [comment]
Hey there, thanks for the helpful gif. I'd also noticed that 404, and I believe I addressed it in b7d983bfd96ddec621e5c2f97bddd70cbbf56858.

Would you mind taking a look to confirm?

**Comment by johhansantana** [comment]
@ginatrapani the body pages list is now working correctly, though the navigation menu pages weren't.

Maybe https://github.com/postlight/headless-wp-starter/pull/23 fixes it?

**Comment by johhansantana** [comment]
![404](https://user-images.githubusercontent.com/9933887/32975538-b3447e5c-cbb4-11e7-87ba-ef5370566e27.gif)

Fixed the menu links but pages links seems to still have the 404 error which is weird. I've updated the PR

**Comment by kozlowskam** [comment]
hello,
I still face this issue. I cloned the repo today.

**Comment by kozlowskam** [comment]
hello,

I still face this issue. I cloned the repo today.
